### ISSUE TITLE
MarkerWithLabel : problem of overlapping labels when two markers are in the same position

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlemaps/v3-utility-library#24]
```
please, Looks this attach file.

Browser / Operating System:
all


*********************************************************
Tip: Star this issue (next to title) to receive notifications of status
changes against this issue, also used as a gauge for how many people are
interested in seeing it resolved.
*********************************************************

```

Original issue reported on code.google.com by `webacte...@gmail.com` on 16 Jul 2010 at 5:08

Attachments:
- [markerlabel.png](https://storage.googleapis.com/google-code-attachments/google-maps-utility-library-v3/issue-24/comment-0/markerlabel.png)

**Comment by dinoo812** [comment]
I have Solved this issue:
My Approch was Like this.

step 1 . Using css i have chnged the marker image(label background)
I have given background image for label by this way
`.gm-style>div>div>div>div+div+div>div>div>div{ add  your css image and properties}`

step 2. In the Default `iconUrl` in the agm-marker add a png transaprent null image, so that the mouse hot point will be on that area.

Just Run Enjoy Its Works For me
![map](https://user-images.githubusercontent.com/17898940/38197957-4d9da862-36a8-11e8-9317-f8863e8fe048.jpg)
