### ISSUE TITLE
Marker Clusterer Plus change icon on hover

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlemaps/v3-utility-library#284]
```
*** Cluster in Marker Clusterer Plus ***

How can I dynamically change the Icon used for a specific Cluster in Marker 
Clusterer Plus for Google Maps V3?

The markers do not seem to expose any methods at all to modify them. I need to 
do something like this (or equivalent).

    google.maps.event.addListener(markerCluster, "mouseover", function (c) {
      c.setIcon(hoverIcon);
    });
    google.maps.event.addListener(markerCluster, "mouseout", function (c) {
      c.setIcon(normalIcon);
    });

```

Original issue reported on code.google.com by `nwaissbl...@gmail.com` on 8 Dec 2013 at 8:24

**Comment by Jessman5** [comment]
This may be a bit late but since this issue is still open I'll post my solution for this.

I have a function for getting the inline code of an svg icon
`var getGoogleClusterInlineSvg = function( color ) {
var encoded = window.btoa( '<svg class="marker-cluster" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="30px" height="30px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve"><circle fill="' + color + '" cx="15" cy="15" r="15"/></svg>' );

return ( 'data:image/svg+xml;base64,' + encoded );
};`

an change the fillcolor of the Icon on mouseover and mouseout by referencing the svg as "new Icon" with another fillcolor
`google.maps.event.addListener( markerCluster, "mouseover", function (c) {
c.clusterIcon_.div_.firstChild.src=getGoogleClusterInlineSvg( '#484B4B' )
});

google.maps.event.addListener( markerCluster, "mouseout", function (c) {
c.clusterIcon_.div_.firstChild.src=getGoogleClusterInlineSvg( '#FF001A' )
});`

**Comment by garylittleRLP** [comment]
Nice job! This same technique would also work for simply changing the src of an IMG. I guess I should add a setClusterIconDiv function to the Cluster object so you can do this independently of internal variable names.
