### ISSUE TITLE
Dynamic Map Service Overlay

### ISSUE THREAD

**Issue by sntran** [googlemaps/v3-utility-library#397]
## Steps to reproduce:

- Opens [Dynamic Map Service Overlay example](https://github.com/googlemaps/v3-utility-library/blob/master/arcgislink/examples/dynamap.html) in the browser.

## Expected result:

See the image overlay.

## Actual result:

- No image overlay.
- Exception from the console:

```
Uncaught TypeError: Cannot read property 'parentNode' of null
    at ImageOverlay.onRemove (arcgislink.js:3742)
```

**Comment by sntran** [comment]
It turns out that the newest version of Google Maps JS API (v3.32) is not compatible. Switching to v3.31 works.

**Comment by haider-ali** [comment]
Today v3.31 is also not working any workaround?

**Comment by michaelwda** [comment]
So, it seems like drawing the ImageOverlay is causing the map's draw event to trigger again and it goes into an infinite loop of adding the overlay and removing the overlay. 

I've got something *working*, but I need to clean it up. There probably needs to be a more extensive update because I bet a lot of things have changed...

Fair warning - this is probably not the appropriate way to fix this...

1.  I'm just leaving the drawing_ flag on until another map event triggers and then I turn it off. This kills the infinite loop.
2.  It also was doing some strange behavior where the bounds kept changing and it flashed as it loaded multiple images. I changed the way the overlay loads and added a 500 millisecond timeout before it displays. 
3. Dragging was causing lots of network calls, so when dragging I just bail out of the whole refresh function.

https://github.com/michaelwda/v3-utility-library/commit/810ad4f89ea9bae8256426f76420c3a43a024b32
