### ISSUE TITLE
Marker Cluster in my google-map is not working correctly

### ISSUE THREAD

**Issue by abdelhakimsalama** [googlemaps/v3-utility-library#413]
hi ,I am trying to implement the Marker Cluster . When i am trying to execute this, it is displaying the Marker but it is not Clustering the Markers. I have tried to fix this but i failed. Can anyone help me how to fix this issue?

i saw a lot of solution , but unfortunately there is no solution for my problem

 i'm a beginner in this field , some push from you will help me a lot 

thank you so much ,

this is the link for my poste

https://stackoverflow.com/questions/49222822/marker-cluster-in-my-google-map-is-not-working-correctly

**Comment by patros** [comment]
You have some simple issues with your code.

This line creates a marker but adds it to the map not the marker clusterer...
    createMarker(latlng, Route, Agence, Secteur, CodeClient, PrecisionGPS, Latitude, Longitude, BarCode, PrenomClient, NumAdresse, Tel, Whatsapp, NbrFrigo, OpenAm, CloseAm, OpenPm, ClosePm, OpenAmVen, CloseAmVen, OpenPmVen, ClosePmVen, OpenAmDim, CloseAmDim, OpenPmDim, ClosePmDim, IMEI, Date_Added);

And this line, inside the for loop, is creating a new marker clusterer without referencing markers, you are referencing markersData...
    var markerCluster = new MarkerClusterer(map, markersData,{imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});

You should create a marker array and add each return value from createMarker to it. Don't worry about adding it to the map yet. Then, instead of passing in markersData pass in the marker array when you are trying to instantiate the marker clusterer. Just make sure you take the marker clusterer line outside of the for loop.

I can give you more specific help but please provide static html, css and js files to reproduce what you are trying.

**Comment by abdelhakimsalama** [comment]
@patros 
thank you sir for your answer ,
sir i have another problem that i try to resolve it from 2 weeks
this is the link for my problem i explain it in github 

https://stackoverflow.com/questions/49988784/display-location-from-my-current-location-to-another-selected-location

please can you help me ??

**Comment by patros** [comment]
This probably isn't the best place for this type of request. Can I suggest that you start by reading through the documentation? There are a lot of good examples throughout. [https://developers.google.com/maps/documentation/javascript/reference/3/](https://developers.google.com/maps/documentation/javascript/reference/3/)
