### ISSUE TITLE
arcgislink error with Google Maps version 3.32

### ISSUE THREAD

**Issue by pogione** [googlemaps/v3-utility-library#432]
The code below returns an error when v=3.32 (or 3.33), while it works fine with 3.31.
I presume changes are needed for the new render and basemap. Any clues?

```
<!DOCTYPE html>
<html>
<head>
  <title>Simple Map</title>
  <meta name="viewport" content="initial-scale=1.0">
  <meta charset="utf-8">
  <style>
    #map2 {
      height: 500px;
      width: 500px
    }
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
  </style>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=xyz&v=3.32"></script>
  <script src="arcgislink_compiled.js"></script>
</head>
<body>
  <div id="map2"></div>
  <h3 id="version"></h3>
  <script>
    var map;
    function initMap()
    {
      map = new google.maps.Map(document.getElementById('map2'), {
        center: { lat: 41.2703, lng: 260.847 },
        zoom: 4
      });
      $("#version").text(google.maps.version);

      var NewOverlay = new gmaps.ags.MapOverlay("https://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StateCityHighway_USA/MapServer",
        {
          exportOptions: {
            layerIds: ["0"],
            layerOption: 'show'
          },
          map: map
        });
    }
    $(function ()
    {
      initMap();
    });
  </script>

</body>
</html>
```

**Comment by domesticmouse** [comment]
It would be really helpful to see the returned error. I'm guessing `arcgislink` is assuming something about our DOM implementation that changed between v3.31 and v3.32.

Can you please raise an issue on our [Google Maps JavaScript API Issue Tracker](https://developers.google.com/maps/documentation/javascript/support#issue-tracker).

Thanks!

**Comment by pogione** [comment]
I changed to non compiled version and Google Chrome says 

> Uncaught TypeError: Cannot read property 'parentNode' of null
>     at ImageOverlay.onRemove (arcgislink.js:3742)

Firefox says

> TypeError: this.div_ is null  arcgislink.js:3742:5

I will raise an issue. Thanks

**Comment by haider-ali** [comment]
@pogione  any update on the issue , i am having same issue

**Comment by BHare1985** [comment]
I vote to reopen this issue as well, google maps recently completely disable the use of old google map versions that work with arcgislink.js

My initial research shows that adding a new `ImageOverlay` calls a draw() on the `MapOverlay`  which in turn causes `MapOverlay.refresh` to trigger which makes all kinds of problems.

Basically `drawing_` is set to false as soon as it gets a json response from export map. The json response is added to the map via `ImageOverlay` constructor which in turn calls the MapOverlay.refresh which attempts to remove the overlay that was just added BEFORE the OnAdd is call, causing the this.div_ to be null.

Removing 
```
    if (!this.dragging && this.overlay_){
      this.overlay_.setMap(null);
      this.overlay_ = null;
    }
```

Fixes the onRemove issue but the MapOverlay's drawing_ variable has to become smarter. I working on setting the `drawing_=false` variable in `ImageOverlay`'s OnAdd function as its not truly done drawing until the OnAdd function has been called.

There are a bunch of other issues also occurring because of the google map update, such as ImageOverlays being off centered, etc.

**Comment by BHare1985** [comment]
Here is an update: https://github.com/googlemaps/v3-utility-library/issues/450

**Comment by pogione** [comment]
Short term fix that works for me is
arcgislink.js at line number 3546

`MapOverlay.prototype.draw = function () {
  if (!this.drawing_ || this.needsNewRefresh_ === true) {
    if (this.overlay_==null) {
      this.refresh();
	}
	}
};
`

**Comment by sivaprakashd** [comment]
@pogione, @BHare1985 I'm still facing the issue.  Can you share arcgislink.js file. Thank you in advance.

**Comment by stephenmcd** [comment]
Just pushed cdde3b2571bf35fee028c3f0edbde81a395a91fa which may resolve the issue - please let me know how this goes.
