### ISSUE TITLE
markerclustererplus vs markerclusterer

### ISSUE THREAD

**Issue by billynoah** [googlemaps/v3-utility-library#461]
Description and documentation aren't really clear about the differences between markerclustererplus and markerclusterer.  Can someone please update them and/or offer something authoritative here to make it clear?

**Comment by garylittleRLP** [comment]
One of the key things is simply the documentation: MarkerClustererPlus has much better documentation. It also handles a large number of markers more efficiently, fixes a few bugs, makes the code more readable, etc. The basic algorithm for clustering remains the same, however, and MarkerClustererPlus was designed to be upward compatible with MarkerClusterer so you can switch from MC to MCP without changing the applications source code.

When I wrote MCP, the people at Google (who wrote MC) wanted me to do a line by line explanation of the differences. I declined because I had made so many changes including rearranging of code that the explanation would have taken forever. Since they wouldn't review the changes, I simply posted as MarkerClustererPlus. This all happened many years ago and I've been using MCP very successfully since then.

**Comment by billynoah** [comment]
Thanks for explaining Gary.  I recently implemented a google maps instance to show locations of orders on our website, with quite a few filter options.  I ended up using markerclusterplus since it has the `clusteringend` event.  This is really helpful since I can select some filters, add a `loading` class, send an ajax call to retrieve markers and then remove the `loading` class on the `clusteringend` event.  It's a simple feature but it makes the UX on map loads that much better.  Also, fwiw, the initial unfiltered map loads approx 50,000 markers and the clusters render in around 2 or 3 seconds — which is awesome!  Just wanted to make mention of how I'm using this extension and say thanks.

**Comment by rdmckelvey** [comment]
I'm eager to try out MarkerClustererPlus and I've seen several statements that it's got "better documentation" than MarkerClusterer, but I'm not able to find any set of instructions or lists of methods/properties for it. Is it that the code itself is better documented, or am I missing a clear reference page somewhere. Thanks for any advice/pointers...

**Comment by rdmckelvey** [comment]
I don't know if this is relevant, but in the README page, under the NPM header, the "Read More" link gives me a "loading..." page that seems to hang indefinitely.

**Comment by garylittleRLP** [comment]
In the previous repository there was a way to create documentation from formatted comments in the source code. That seems to have disappeared in GitHub. The best way to see the documentation is to review the comments in the source code. All the usage details are there.

**Comment by rdmckelvey** [comment]
Thank you for the quick and clear reply! I’ll look there.

Best,

Roy McKelvey
Web Designer

Communication Design, Inc.
3300 West Broad Street
Suite 204
Richmond, VA 23230
804.354.5335

www.communicationdesign.com

Marketing Materials • Magazines & Newsletters • Corporate Identities • Print Ads • Illustration • Web Sites

**Comment by yogigachinmath** [comment]
can anyone providr the link for mcp documentation !!

**Comment by wooliet** [comment]
Here's one way to view formatted documentation using [jsdoc](https://www.npmjs.com/package/jsdoc)

```
> git clone https://github.com/googlemaps/v3-utility-library.git
> cd v3-utility-library/packages/markerclustererplus/src
> npx jsdoc markerclusterer.js
```

The result is _./out/index.html_.

**Comment by jpoehnelt** [comment]
see https://github.com/googlemaps/v3-utility-library/issues/579

**Comment by jpoehnelt** [comment]
@google/markerclustererplus documentation now available at :https://googlemaps.github.io/v3-utility-library/modules/_google_markerclustererplus.html
