### ISSUE TITLE
Issues with clustering markers and pinch zoom on mobile

### ISSUE THREAD

**Issue by flojon** [googlemaps/v3-utility-library#481]
Hi, 

We have noticed a problem with clustering markers in our app. But we saw that the same problem happens with the example map at: 
https://developers.google.com/maps/documentation/javascript/marker-clustering 

First issue: 
If you put one finger on one clustering marker and another finger on another clustering marker and then pinch to zom in. After a short while the zoom will stop and all the clustering markers will dissapear. They show up again if you pan or adjust the zoom. 

Second issue: 
Sometimes when we try to pinch to zoom and happen to put one finger on a clustering marker the map will zoom out completly to the world map. We haven't figured out completly what triggers it. If it's certain spot on the clustering marker. But it will happen maybee 1 time in 10 tries... 

Both issues can happen on both iOS and Android. 

In our application we have a lot of clustering markers so the problem happens more frequently.

**Comment by alexmccabe** [comment]
We are experiencing this exact same issue and are currently going to investigate whether there is a workaround / solution.

**Comment by alexmccabe** [comment]
Findings from my investigation:

Map has touch listeners applied to know when to zoom, so `touches.length > 1 ? doZoom : doNotZoom`. Cluster has event propagation so it bubbles the event up to the map, but the touch event is _registered_ on the cluster. When you zoom the cluster is removed, so consequently the event is removed, because that is good practice. This removes the `touchmove` listener and because the `touchmove` has been removed, the `maps.event.addListener(Map, ‘idle’, ...) event is never triggered because the map thinks it’s still being interacted with.

Thing is, the cluster _should not_ be removed *until* the `idle` event has been triggered, as this triggers a redraw.

Things that trigger a cluster redraw:
- Adding markers
- Adding a single marker
- Removing a single marker
- Removing markers
- When the map becomes ‘idle’
- A repaint (which we never trigger as we don’t have draggable markers)

Things I did to debug:
- We are not triggering a cluster redraw mid-move.
- I logged every instance of the cluster redraw, and the clusters are not being redrawn
- Neither then MarkerClusterer or the Clusterer classes is not being reinitialised at any point

I thought it could be something that we were doing that could trigger the markers to be removed, but it's not. It's also apparently nothing that the library is doing (that I can see). The markers are just removed from the DOM when zooming.

The cause of the issue:
All of the clusters are removed and re-added on `zoom_changed` with not throttling of the event. This is the problem. The markers should not be re-drawn until the user has finished interacting with the map. The `zoom_changed` event should be throttled or debounced.

**Comment by alexmccabe** [comment]
@flojon We have a workaround if you're interested!

1) Remove the `zoom_changed` listener starting line `163`.
2) Change the `idle` listener to the following: 

```js
  google.maps.event.addListener(this.map_, 'idle', function() {
    that.resetViewport();
    that.redraw();
  });
```

**Comment by flojon** [comment]
@alexmccabe Thank you for your help! I finally tried your workaround. I noticed we actually use MarkerClusterPlus so I changed the `idle` listener to this:
```
        google.maps.event.addListener(this.getMap(), "idle", function () {
            cMarkerClusterer.resetViewport_();
            cMarkerClusterer.redraw_();
        })
```
There is one issue with this workaround. If I put my fingers on two cluster marker or two fingers on the same cluster marker and zoom it will "zoom" into the cluster marker, ie, make it bigger, instead of zoom into the map... To reset it I have to double touch on a cluster marker.

**Comment by alexmccabe** [comment]
I've replaced that code inside googles code, but by the sounds of it you're trying to overload their listener with yours, which I don't think will work and will probably result in the issue you are having. 

I cloned the google maps library and we now maintain our own version of it, with my previous workaround.

**Comment by flojon** [comment]
I replaced the code inside markercluster.js here: https://github.com/googlemaps/v3-utility-library/blob/66d4921aba3c0d5aa24d5998e485f46c34a6db27/markerclustererplus/src/markerclusterer.js#L754-L770
We have a copy of that file in our repository.
I removed the `zoom_changed` listener and modified the `idle` listener.
Is your clone public?

**Comment by alexmccabe** [comment]
https://gist.github.com/alexmccabe/510dc73e27c7c04be669dff96f0acbd9

Here you go buddy

**Comment by ruisilva450** [comment]
Could this be made into a PR?
I don't find any downside of the @alexmccabe version

**Comment by jeanmatthieud** [comment]
I believe the issue still exists: on mobile, trying to zoom or pan with a finger on a cluster fails.

**Comment by alexmccabe** [comment]
Sorry I didn't get around to opening a PR for this, and now I'm totally out of the loop in what the original problem was (I've switched jobs multiple times since then, pandemic for you). @jeanmatthieud It's not ideal, but the workaround I posted seems to have worked for at least one other person. Maybe you could check the gist I posted? It seems there hasn't been any changes to the core lib so you could replace the package version in it's entirety with the version I posted. You could look into [patch package](https://www.npmjs.com/package/patch-package) to make it easier?

**Comment by jhappone** [comment]
Hi!

I'm having this same issue with the latest version too with the https://github.com/googlemaps/js-markerclustererplus Everything works fine on desktop. In the mobile, if you pinch zoom by **not** touching the cluster-icons, it works, but if you pinch zoom over marker icon, depending on the meta viewport settings, it either zooms the whole viewport or does not zoom at all.

I had implemented the latest version of markerclustererplus with hiding/showing markers inside cluster and it worked fine (except pinch zoom on mobile),  and when I tried @alexmccabe version (https://gist.github.com/alexmccabe/510dc73e27c7c04be669dff96f0acbd9) pinch zooming started working but marker hiding/showing did not work.

I'm kinda stuck now between these two versions. I need to either try to get "old" version working with my marker hiding/showing code, or hopefully get the latest version working with pinch zoom.

I'm happy to help if needed.

Br,
Jukka
